<MyGrid>

    name: nameID
    email: emailID

    GridLayout:
        cols: 1
        size: root.width - 200, root.height - 200
        pos: 100, 100

        GridLayout:
            cols: 2

            Label:
                text: "Last Name: "

            TextInput:
                id: nameID
                multiline: False

            Label:
                text: "Email: "
            
            TextInput:
                id: emailID
                multiline: False
        
        Button:
            text: "Submit"
            on_press: root.btn()